[package]
name = "untitled-4"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
futures = "0.3.31"
nannou = "0.19.0"
nannou_wgpu = "0.19.0"
tokio = { version = "1.43.0", features = ["full"] }
